server:
    applicationConnectors:
        - type: http
          port: 8777
    adminConnectors:
        - type: http
          port: 8779

microDepServiceConfiguration:
    zookeeperUrl: tcp://zookeeper.microhackathon.pl:2181
    microserviceContext: twitter-topics-analyzer
    microserviceUrl: localhost
    microservicePort: 8777

logging:
  level: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: logs/application.log
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSSZ, Europe/Warsaw} | %-5level | %X{correlationId} | %thread | %logger{1} | %m%n"
      archive: false
    - type: console
      threshold: INFO
      timeZone: UTC
      target: stdout
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSSZ, Europe/Warsaw} | %-5level | %X{correlationId} | %thread | %logger{1} | %m%n"